---
  - name: Hosts run on Ubuntu
    hosts: all
    become: false
    roles:
      - common

  - name: irods client
    hosts: my_irods
    roles:
      - irods-client

  - name: install singularity container
    hosts: my_irods
    roles:
      - container
