---
IRODS_FETCH_VERSION: "{{ IRODS_VERSION }}"

IRODS_DB_PLUGIN_VERSION:
  4.1.0: "1.5"
  4.1.1: "1.5"
  4.1.2: "1.5"
  4.1.3: "1.5"
  4.1.4: "1.5"
  4.1.5: "1.6"
  4.1.6: "1.6"
  4.1.7: "1.7"
  4.1.8: "1.8"
  4.1.9: "1.9"
  4.1.10: "1.10"

IRODS_CURRENT_INSTALL_OS: "{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}"
IRODS_RELEASES_BASE_URL: "ftp://ftp.renci.org/pub/irods/releases/{{ IRODS_VERSION }}/{{ IRODS_CURRENT_INSTALL_OS }}"
IRODS_DEB_URL: "{{ IRODS_RELEASES_BASE_URL }}/{{ IRODS_DEB }}-{{ IRODS_FETCH_VERSION }}-{{ IRODS_CURRENT_INSTALL_OS }}-x86_64"
