---

  - name: Install epel release (Redhat).
    become: true
    yum: name=epel-release state=present
    when: ansible_pkg_mgr == "yum"

  - include: add-apt-cache.yml
    become: true
    when: COMMON_APT_ADD_CACHE == true and ansible_pkg_mgr == "apt"

  - include: update.yml
    become: true

  - name: Install common packages.
    become: true
    package: name={{ item }} state=present
    with_items:
      - acl
      - rsync
      - ntp
      - htop
      - nano
      - openssl
      - screen
      - mc
      - x11-apps

  - name: Deploy .screenrc to the home.
    copy:
      src: files/.screenrc
      dest: "{{ ansible_env.HOME }}"

