---

  - name: Update apt cache.
    apt: update_cache=yes cache_valid_time=86400
    when: ansible_pkg_mgr == "apt"

  - name: Upgrade apt packages.
    apt: upgrade=yes
    when:
      - COMMON_PACKAGE_UPGRADE
      - ansible_pkg_mgr == "apt"

  - name: Upgrade yum packages.
    yum: name='*' state=latest update_cache=yes
    when:
      - COMMON_PACKAGE_UPGRADE
      - ansible_pkg_mgr == "yum"


